# 配置端口
server:
  port: 8888
  servlet:
    context-path: /api/v1

spring:
  # 配置数据库连接信息
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online_exam_sys
    username: root
    password: root
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
    servlet:
      load-on-startup: 1
    static-path-pattern: /static/**

# JWT配置
jwt:
  # 密匙KEY
  secret: JwtSecret
  # HeaderKEY
  tokenHeader: Authorization
  # 过期时间 单位秒 1天后过期=86400 7天后过期=604800
  expiration: 86400

# Mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper所对应的XML文件位置）
  mapper-locations: classpath:mapper/**/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.xin.online_exam_sys.pojo